config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get 'friends/index'
  # get 'friends/show'
  # get 'friends/new'
  # get 'persons/index'
  # get 'persons/show'
  # get 'persons/new'

  resources :friends
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  def full_name
    # Person.find(params[:first_name]) + " " + Person.find(params[:last_name])
    self.first_name + " " + self.last_name
  end
end

app/models/person.rb
class Person < ApplicationRecord

  def full_name
    # Person.find(params[:first_name]) + " " + Person.find(params[:last_name])
    self.first_name + " " + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

    def index
      @friends = Friend.all
    end

    def show
      @friend = Friend.find(params[:id])
    end

    def new
      @friend = Friend.new
      render partial: "form"
    end

    def edit
      @friend = Friend.find(params[:id])
      render partial: "form"
    end

    def update
      @friend = Friend.find(params[:id])
      if @friend.update(friend_params)
        redirect_to friends_path
      else
        render :new
      end
    end

    def destroy
      @friend = Friend.find(params[:id]).destroy
      redirect_to friends_path
    end

    def create
      @friend = Friend.new(friend_params)
      if @friend.save
        redirect_to friends_path
      else
        render :new
      end
    end

    private

    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender, :birth, :living)
    end




  end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController

  def index
    @persons = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
    render partial: "form"
  end

  def edit
    @person = Person.find(params[:id])
    render partial: "form"
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to persons_path
    else
      render :new
    end
  end

  def destroy
    @person = Person.find(params[:id]).destroy
    redirect_to persons_path
  end

  private

  def person_params
    params.require(:person).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender, :alive)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/friends/_form.html.erb
<%= form_for @friend do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name %>

<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= f.label "Year Born" %>
<%= f.date_field :birth %>

<%= f.label :age %>
<%= f.text_field :age %>
 <%# <% (date_of_birth = :alive) %>
<%# <% :age = (Time.zone.now - date_of_birth) %>

<%= f.label :hair_color %>
<%= f.text_field :hair_color %>

<%= f.label :eye_color %>
<%= f.text_field :eye_color %>

<%= f.label :living %>
<%= f.check_box :living %>

<%= f.submit %>
<%= link_to 'back', friends_path %>
<% end %>

app/views/friends/index.html.erb
<h1>All the People!</h1>
<h2>List of people</h2>
<h3><%= link_to 'Create a new Entry', new_friend_path %></h3>
<% @friends.each do |friend| %>
  <h3> <%= friend.full_name %></h3>
  <%= link_to 'Details', friend_path(friend) %>
  <%= link_to 'Edit', edit_friend_path(friend) %>
  <%= link_to 'Delete', friend_path(friend), method: :delete %>
<% end %>

app/views/friends/new.html.erb
<h1> Create a new Person! </h1>

app/views/friends/show.html.erb
<h1>
  <%= @friend.full_name %></h1>
<p>Age:
  <%= @friend.age %></p>
<p>Hair Color:
  <%= @friend.hair_color %></p>
<p>Eye Color:
  <%= @friend.eye_color %></p>
<p>Birth Date:
  <%= @friend.birth %>
</p>
<p>

  <% if @friend.living == true %>
    <div><%=@friend.full_name%> is alive and kicking!</div>
  <% else %>
    <div><%=@friend.full_name%> died. Weird that you didn't know that.</div>
  <% end %>
</p>
<%= link_to 'back', friends_path %>
<%= link_to 'Edit', edit_friend_path(@friend) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/persons/_form.html.erb
<%= form_for @person do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name %>

<%= f.label :last_name %>
<%= f.text_field :last_name %>

<%= f.label "Year Born" %>
<%= f.date_field :alive %>

<%= f.label :age %>
<%= f.text_field :age %>
 <%# <% (date_of_birth = :alive) %>
<%# <% :age = (Time.zone.now - date_of_birth) %>

<%= f.label :hair_color %>
<%= f.text_field :hair_color %>

<%= f.label :hair_color %>
<%= f.text_field :hair_color %>

<%= f.submit %>
<% end %>

app/views/persons/index.html.erb
<h1>All the People!</h1>
<h2>List of people</h2>
<h3><%= link_to 'Create a new Entry', new_person_path %></h3>
<% @persons.each do |person| %>
  <h3> <%= person.full_name %></h3>
  <%= link_to 'Show Full Details', person_path(person) %>
  <%= link_to 'Edit', edit_person_path(person) %>
  <%= link_to 'Delete', person_path(person), method: :delete %>
<% end %>

app/views/persons/new.html.erb
<h1>Persons#new</h1>
<p>Find me in app/views/persons/new.html.erb</p>

app/views/persons/show.html.erb
<h1> <%= @friend.full_name %></h1>
<p>Age: <%= @friend.age %></p>
<p>Hair Color: <%= @friend.hair_color %></p>
<p>Eye Color: <%= @friend.eye_color %></p>
<p>Birth Date: <%= @friend.alive %> </p>

<%= link_to 'Edit', edit_friend_path(@friend) %>